/**
 * 
 */
var tb_icon_button = null;
if (typeof window.tb_icon_button_disable == 'undefined') window.tb_icon_button_disable = false;
(function() {
    tinymce.PluginManager.add('tb_icon',function(editor, url) {
    	editor.addButton('tb_icon', {
            title : 'Add an Icon',
            image : url+'/img/icon_icon.png',
            onPostRender: function() { 
            		tb_icon_button = this;
            		tb_icon_button.disabled(tb_icon_button_disable);
            	},
            onclick : function() {
            	
            	//editor.selection.setContent('[icon]');
            	
            	// Open window
                editor.windowManager.open({
                    title: 'Bootstrap Icon (see http://getbootstrap.com/components/)',
                    body: [
                        {type: 'listbox', name: 'glyph', label: 'Icons', 'values': [
																					{text: 'adjust', value: 'adjust'},
																					{text: 'alert', value: 'alert'},
																					{text: 'align-center', value: 'align-center'},
																					{text: 'align-justif', value: 'align-justif'},
																					{text: 'align-left', value: 'align-left'},
																					{text: 'align-right', value: 'align-right'},
																					{text: 'apple', value: 'apple'},
																					{text: 'arrow-down', value: 'arrow-down'},
																					{text: 'arrow-left', value: 'arrow-left'},
																					{text: 'arrow-right', value: 'arrow-right'},
																					{text: 'arrow-up', value: 'arrow-up'},
																					{text: 'asterisk', value: 'asterisk'},
																					{text: 'baby-formula', value: 'baby-formula'},
																					{text: 'backward', value: 'backward'},
																					{text: 'ban-circle', value: 'ban-circle'},
																					{text: 'barcode', value: 'barcode'},
																					{text: 'bed', value: 'bed'},
																					{text: 'bell', value: 'bell'},
																					{text: 'bishop', value: 'bishop'},
																					{text: 'bitcoin', value: 'bitcoin'},
																					{text: 'blackboard', value: 'blackboard'},
																					{text: 'bold', value: 'bold'},
																					{text: 'book', value: 'book'},
																					{text: 'bookmark', value: 'bookmark'},
																					{text: 'briefcase', value: 'briefcase'},
																					{text: 'btc', value: 'btc'},
																					{text: 'bullhorn', value: 'bullhorn'},
																					{text: 'calendar', value: 'calendar'},
																					{text: 'camera', value: 'camera'},
																					{text: 'cd', value: 'cd'},
																					{text: 'certificat', value: 'certificat'},
																					{text: 'check', value: 'check'},
																					{text: 'chevron-down', value: 'chevron-down'},
																					{text: 'chevron-left', value: 'chevron-left'},
																					{text: 'chevron-right', value: 'chevron-right'},
																					{text: 'chevron-up', value: 'chevron-up'},
																					{text: 'circle-arrow-down', value: 'circle-arrow-down'},
																					{text: 'circle-arrow-left', value: 'circle-arrow-left'},
																					{text: 'circle-arrow-right', value: 'circle-arrow-right'},
																					{text: 'circle-arrow-up', value: 'circle-arrow-up'},
																					{text: 'cloud', value: 'cloud'},
																					{text: 'cloud-download', value: 'cloud-download'},
																					{text: 'cloud-upload', value: 'cloud-upload'},
																					{text: 'cog', value: 'cog'},
																					{text: 'collapse-down', value: 'collapse-down'},
																					{text: 'collapse-up', value: 'collapse-up'},
																					{text: 'comment', value: 'comment'},
																					{text: 'compressed', value: 'compressed'},
																					{text: 'console', value: 'console'},
																					{text: 'copy', value: 'copy'},
																					{text: 'copyright-mark', value: 'copyright-mark'},
																					{text: 'credit-card', value: 'credit-card'},
																					{text: 'cutlery', value: 'cutlery'},
																					{text: 'dashboard', value: 'dashboard'},
																					{text: 'download', value: 'download'},
																					{text: 'download-alt', value: 'download-alt'},
																					{text: 'duplicate', value: 'duplicate'},
																					{text: 'earphone', value: 'earphone'},
																					{text: 'edit', value: 'edit'},
																					{text: 'education', value: 'education'},
																					{text: 'eject', value: 'eject'},
																					{text: 'envelope', value: 'envelope'},
																					{text: 'equalizer', value: 'equalizer'},
																					{text: 'erase', value: 'erase'},
																					{text: 'eur', value: 'eur'},
																					{text: 'euro', value: 'euro'},
																					{text: 'exclamation-sign', value: 'exclamation-sign'},
																					{text: 'expand', value: 'expand'},
																					{text: 'export', value: 'export'},
																					{text: 'eye-close', value: 'eye-close'},
																					{text: 'eye-open', value: 'eye-open'},
																					{text: 'facetime-video', value: 'facetime-video'},
																					{text: 'fast-backward', value: 'fast-backward'},
																					{text: 'fast-forward', value: 'fast-forward'},
																					{text: 'file', value: 'file'},
																					{text: 'film', value: 'film'},
																					{text: 'filter', value: 'filter'},
																					{text: 'fire', value: 'fire'},
																					{text: 'flag', value: 'flag'},
																					{text: 'flash', value: 'flash'},
																					{text: 'floppy-disk', value: 'floppy-disk'},
																					{text: 'floppy-open', value: 'floppy-open'},
																					{text: 'floppy-remove', value: 'floppy-remove'},
																					{text: 'floppy-save', value: 'floppy-save'},
																					{text: 'floppy-saved', value: 'floppy-saved'},
																					{text: 'folder-close', value: 'folder-close'},
																					{text: 'folder-open', value: 'folder-open'},
																					{text: 'font', value: 'font'},
																					{text: 'forward', value: 'forward'},
																					{text: 'fullscreen', value: 'fullscreen'},
																					{text: 'gbp', value: 'gbp'},
																					{text: 'gift', value: 'gift'},
																					{text: 'glass', value: 'glass'},
																					{text: 'globe', value: 'globe'},
																					{text: 'grain', value: 'grain'},
																					{text: 'hand-down', value: 'hand-down'},
																					{text: 'hand-left', value: 'hand-left'},
																					{text: 'hand-right', value: 'hand-right'},
																					{text: 'hand-up', value: 'hand-up'},
																					{text: 'hd-video', value: 'hd-video'},
																					{text: 'hdd', value: 'hdd'},
																					{text: 'header', value: 'header'},
																					{text: 'headphones', value: 'headphones'},
																					{text: 'heart', value: 'heart'},
																					{text: 'heart-empty', value: 'heart-empty'},
																					{text: 'home', value: 'home'},
																					{text: 'hourglass', value: 'hourglass'},
																					{text: 'ice-lolly', value: 'ice-lolly'},
																					{text: 'ice-lolly-tasted', value: 'ice-lolly-tasted'},
																					{text: 'import', value: 'import'},
																					{text: 'inbox', value: 'inbox'},
																					{text: 'indent-left', value: 'indent-left'},
																					{text: 'indent-right', value: 'indent-right'},
																					{text: 'info-sign', value: 'info-sign'},
																					{text: 'italic', value: 'italic'},
																					{text: 'jpy', value: 'jpy'},
																					{text: 'king', value: 'king'},
																					{text: 'knight', value: 'knight'},
																					{text: 'lamp', value: 'lamp'},
																					{text: 'leaf', value: 'leaf'},
																					{text: 'level-up', value: 'level-up'},
																					{text: 'link', value: 'link'},
																					{text: 'list', value: 'list'},
																					{text: 'list-alt', value: 'list-alt'},
																					{text: 'lock', value: 'lock'},
																					{text: 'log-in', value: 'log-in'},
																					{text: 'log-out', value: 'log-out'},
																					{text: 'magnet', value: 'magnet'},
																					{text: 'map-marker', value: 'map-marker'},
																					{text: 'menu-down', value: 'menu-down'},
																					{text: 'menu-hamburger', value: 'menu-hamburger'},
																					{text: 'menu-left', value: 'menu-left'},
																					{text: 'menu-right', value: 'menu-right'},
																					{text: 'menu-up', value: 'menu-up'},
																					{text: 'minus', value: 'minus'},
																					{text: 'minus-sign', value: 'minus-sign'},
																					{text: 'modal-window', value: 'modal-window'},
																					{text: 'move', value: 'move'},
																					{text: 'music', value: 'music'},
																					{text: 'new-window', value: 'new-window'},
																					{text: 'object-align-bottom', value: 'object-align-bottom'},
																					{text: 'object-align-horizontal', value: 'object-align-horizontal'},
																					{text: 'object-align-left', value: 'object-align-left'},
																					{text: 'object-align-right', value: 'object-align-right'},
																					{text: 'object-align-top', value: 'object-align-top'},
																					{text: 'object-align-vertical', value: 'object-align-vertical'},
																					{text: 'off', value: 'off'},
																					{text: 'oil', value: 'oil'},
																					{text: 'ok', value: 'ok'},
																					{text: 'ok-circle', value: 'ok-circle'},
																					{text: 'ok-sign', value: 'ok-sign'},
																					{text: 'open', value: 'open'},
																					{text: 'open-file', value: 'open-file'},
																					{text: 'option-horizontal', value: 'option-horizontal'},
																					{text: 'option-vertical', value: 'option-vertical'},
																					{text: 'paperclip', value: 'paperclip'},
																					{text: 'paste', value: 'paste'},
																					{text: 'pause', value: 'pause'},
																					{text: 'pawn', value: 'pawn'},
																					{text: 'pencil', value: 'pencil'},
																					{text: 'phone', value: 'phone'},
																					{text: 'phone-alt', value: 'phone-alt'},
																					{text: 'picture', value: 'picture'},
																					{text: 'piggy-bank', value: 'piggy-bank'},
																					{text: 'plane', value: 'plane'},
																					{text: 'play', value: 'play'},
																					{text: 'play-circle', value: 'play-circle'},
																					{text: 'plus', value: 'plus'},
																					{text: 'plus-sign', value: 'plus-sign'},
																					{text: 'print', value: 'print'},
																					{text: 'pushpin', value: 'pushpin'},
																					{text: 'qrcode', value: 'qrcode'},
																					{text: 'queen', value: 'queen'},
																					{text: 'question-sign', value: 'question-sign'},
																					{text: 'random', value: 'random'},
																					{text: 'record', value: 'record'},
																					{text: 'refresh', value: 'refresh'},
																					{text: 'registration-mark', value: 'registration-mark'},
																					{text: 'remove', value: 'remove'},
																					{text: 'remove-circle', value: 'remove-circle'},
																					{text: 'remove-sign', value: 'remove-sign'},
																					{text: 'repeat', value: 'repeat'},
																					{text: 'resize-full', value: 'resize-full'},
																					{text: 'resize-horizontal', value: 'resize-horizontal'},
																					{text: 'resize-small', value: 'resize-small'},
																					{text: 'resize-vertical', value: 'resize-vertical'},
																					{text: 'retweet', value: 'retweet'},
																					{text: 'road', value: 'road'},
																					{text: 'rub', value: 'rub'},
																					{text: 'ruble', value: 'ruble'},
																					{text: 'save', value: 'save'},
																					{text: 'save-file', value: 'save-file'},
																					{text: 'saved', value: 'saved'},
																					{text: 'scale', value: 'scale'},
																					{text: 'scissors', value: 'scissors'},
																					{text: 'screenshot', value: 'screenshot'},
																					{text: 'sd-video', value: 'sd-video'},
																					{text: 'search', value: 'search'},
																					{text: 'send', value: 'send'},
																					{text: 'share', value: 'share'},
																					{text: 'share-alt', value: 'share-alt'},
																					{text: 'shopping-cart', value: 'shopping-cart'},
																					{text: 'signal', value: 'signal'},
																					{text: 'sort', value: 'sort'},
																					{text: 'sort-by-alphabet', value: 'sort-by-alphabet'},
																					{text: 'sort-by-alphabet-alt', value: 'sort-by-alphabet-alt'},
																					{text: 'sort-by-attributes', value: 'sort-by-attributes'},
																					{text: 'sort-by-attributes-alt', value: 'sort-by-attributes-alt'},
																					{text: 'sort-by-order', value: 'sort-by-order'},
																					{text: 'sort-by-order-alt', value: 'sort-by-order-alt'},
																					{text: 'sound-5-1', value: 'sound-5-1'},
																					{text: 'sound-6-1', value: 'sound-6-1'},
																					{text: 'sound-7-1', value: 'sound-7-1'},
																					{text: 'sound-dolby', value: 'sound-dolby'},
																					{text: 'sound-stereo', value: 'sound-stereo'},
																					{text: 'star', value: 'star'},
																					{text: 'star-empty', value: 'star-empty'},
																					{text: 'stats', value: 'stats'},
																					{text: 'step-backward', value: 'step-backward'},
																					{text: 'step-forward', value: 'step-forward'},
																					{text: 'stop', value: 'stop'},
																					{text: 'subscript', value: 'subscript'},
																					{text: 'subtitles', value: 'subtitles'},
																					{text: 'sunglasses', value: 'sunglasses'},
																					{text: 'superscript', value: 'superscript'},
																					{text: 'tag', value: 'tag'},
																					{text: 'tags', value: 'tags'},
																					{text: 'tasks', value: 'tasks'},
																					{text: 'tent', value: 'tent'},
																					{text: 'text-background', value: 'text-background'},
																					{text: 'text-color', value: 'text-color'},
																					{text: 'text-height', value: 'text-height'},
																					{text: 'text-size', value: 'text-size'},
																					{text: 'text-width', value: 'text-width'},
																					{text: 'th', value: 'th'},
																					{text: 'th-large', value: 'th-large'},
																					{text: 'th-list', value: 'th-list'},
																					{text: 'thumbs-down', value: 'thumbs-down'},
																					{text: 'thumbs-up', value: 'thumbs-up'},
																					{text: 'time', value: 'time'},
																					{text: 'tint', value: 'tint'},
																					{text: 'tower', value: 'tower'},
																					{text: 'transfer', value: 'transfer'},
																					{text: 'trash', value: 'trash'},
																					{text: 'tree-conifer', value: 'tree-conifer'},
																					{text: 'tree-deciduous', value: 'tree-deciduous'},
																					{text: 'triangle-bottom', value: 'triangle-bottom'},
																					{text: 'triangle-left', value: 'triangle-left'},
																					{text: 'triangle-right', value: 'triangle-right'},
																					{text: 'triangle-top', value: 'triangle-top'},
																					{text: 'unchecked', value: 'unchecked'},
																					{text: 'upload', value: 'upload'},
																					{text: 'usd', value: 'usd'},
																					{text: 'user', value: 'user'},
																					{text: 'volume-down', value: 'volume-down'},
																					{text: 'volume-off', value: 'volume-off'},
																					{text: 'volume-up', value: 'volume-up'},
																					{text: 'warning-sign', value: 'warning-sign'},
																					{text: 'wrench', value: 'wrench'},
																					{text: 'xbt', value: 'xbt'},
																					{text: 'yen', value: 'yen'},
																					{text: 'zoom-in', value: 'zoom-in'},
																					{text: 'zoom-out', value: 'zoom-out'},
																					{text: 'adjust', value: 'adjust'},
                                                                                    ]},
                    ],
                    onsubmit: function(e) {
                    	shortcode = '[tb-icon glyph="' + e.data.glyph + '" ]';                    	
                        editor.selection.setContent(shortcode);
                    }
                });

            }
        });
    });
})();

